export interface BacklogItem {
  id: string;
  key: string;
  project: 'GUAKI' | 'LANZA' | 'VEYRA' | 'MAPACHE' | 'TRINIDAD' | 'BRENDA';
  title: string;
  owner: string;
  priority: 'P0' | 'P1' | 'P2';
  state: 'BACKLOG' | 'PENDIENTE' | 'EN_PROGRESO' | 'PASS';
  tone: 'slate' | 'blue' | 'amber' | 'green';
  description: string;
  acceptanceCriteria: string[];
  nextAction: string;
  targetSprint?: string;
  createdAt: string;
  completedAt?: string;
}

export const INITIAL_ECOSYSTEM_BACKLOG: BacklogItem[] = [
  // ── 🦜 GUAKI MARKETPLACE & CRECIMIENTO ──
  {
    id: 'GKI-01',
    key: 'guaki_directory_ingest',
    project: 'GUAKI',
    title: 'Ingesta y Expansión Masiva del Directorio por Ciudades',
    owner: 'Producto + Scraping',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Poblar el catálogo de proveedores verificados en Medellín, Cali, Bogotá y Barranquilla con datos reales de contacto y geolocalización.',
    acceptanceCriteria: [
      'Al menos 50 proveedores verificados por ciudad principal',
      'Sin datos inventados ni números placeholders',
      'Geolocalización por coordenadas y barrios reales (355 negocios reales capturados)',
    ],
    nextAction: '355 negocios reales en PostgreSQL 5435 sincronizados con Guaki.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'GKI-02',
    key: 'guaki_audit_center_resilience',
    project: 'GUAKI',
    title: 'Centro de Auditoría y Verificación de Proveedores',
    owner: 'Admin + Seguridad',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Panel de revisión técnica de proveedores con aprobación y publicación en 1 clic en el marketplace público.',
    acceptanceCriteria: [
      'Manejo seguro de cola de auditoría (safeQueue sin crasheos)',
      'Acciones de Aprobación, Solicitud de Cambios y Rechazo con notas',
      'Diseño Obsidian Dark Glass unificado',
    ],
    nextAction: 'Centro de Auditoría operando en /command-center.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'GKI-03',
    key: 'guaki_provider_portal_onboarding',
    project: 'GUAKI',
    title: 'Portal de Proveedores: Onboarding y Auto-gestión',
    owner: 'Frontend + UX',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Permitir a los dueños de negocios gestionar su perfil, catálogo de servicios, horarios y métricas de contacto.',
    acceptanceCriteria: [
      'Ruta /provider/dashboard operativa y estilizada',
      'Editor de servicios con fotos y botones directos a WhatsApp',
      'Panel de visualizaciones y clics a WhatsApp',
    ],
    nextAction: 'Ruta /provider/dashboard activa y compilada.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },

  // ── 🦝 MAPACHE + HERMES MOTOR DE PROSPECCIÓN ──
  {
    id: 'MAP-01',
    key: 'tenant',
    project: 'MAPACHE',
    title: 'Tenant y RLS de Mapache',
    owner: 'Producto + Mapache',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Aislamiento multi-tenant estricto con Row Level Security para separar prospectos de Veyra, Lanza y Guaki.',
    acceptanceCriteria: [
      'Políticas RLS activas en Postgres',
      'Validación de JWT con tenant_id obligatorio',
      'Test de penetración multi-tenant en verde',
    ],
    nextAction: 'Suite de pruebas de aislamiento superada.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-16',
  },
  {
    id: 'MAP-02',
    key: 'email',
    project: 'MAPACHE',
    title: 'Correo profesional en Mapache',
    owner: 'Mapache + Operador',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Conexión SMTP autenticada con Hostinger (edwin@veyrasoluciones.com:465 TLS) para envíos transaccionales con DKIM/SPF/DMARC.',
    acceptanceCriteria: [
      'Almacenamiento seguro de credencial en variables de entorno',
      'Envíos entregados y verificados en cuentas de prueba y prospectos reales',
      'Rate limiting configurado',
    ],
    nextAction: '41 correos SMTP despachados con éxito.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'MAP-03',
    key: 'provider',
    project: 'MAPACHE',
    title: 'Proveedor de Discovery y Scraping Activo',
    owner: 'Mapache',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Motor Playwright headless para captura continua de Google Maps rotando por 8 verticales.',
    acceptanceCriteria: [
      'Validación de health sin exponer tokens',
      'Deduplicación por dominio y teléfono',
      '355 empresas persistidas con procedencia real',
    ],
    nextAction: 'Discovery daemon corriendo en background.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'MAP-04',
    key: 'mapache_ai_lead_enrichment',
    project: 'MAPACHE',
    title: 'Enriquecimiento y Calificación de Leads con IA (DQS)',
    owner: 'IA + Mapache',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Auditoría automática de número de reseñas, rating y presencia web para calcular DQS y derivar a LANZA, GUAKI o VEYRA.',
    acceptanceCriteria: [
      'Scoring de velocidad web, número de reseñas y rating',
      'Generación de gancho comercial según debilidad detectada',
      'Enrutamiento automático al pilar correspondiente',
    ],
    nextAction: 'Clasificador automático integrado.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },

  // ── 🏢 VEYRA ENTERPRISE IA & TRANSFORMACIÓN ──
  {
    id: 'VEY-01',
    key: 'template',
    project: 'VEYRA',
    title: 'Plantilla Veyra en CRM y Reportes Business MRI™',
    owner: 'Veyra',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Estandarización de plantillas de diagnóstico Business MRI con variables de ROI, cuellos de botella y oferta High-Ticket ($2.850 USD).',
    acceptanceCriteria: [
      'Render HTML y texto plano consistentes',
      'Variables de personalización aprobadas',
      'Despacho verificado a 31 empresas clasificadas',
    ],
    nextAction: 'Secuencias despachadas por Hostinger SMTP.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'VEY-02',
    key: 'clean_pipeline_real_leads',
    project: 'VEYRA',
    title: 'Limpieza de Mocks y Conexión de Pipeline Real',
    owner: 'Veyra + Producto',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Eliminación total de diagnósticos sintéticos/demo y conexión al pipeline real de $88,350 USD en PostgreSQL 5435.',
    acceptanceCriteria: [
      'Store limpio sin datos de cartón',
      'Carga instantánea sin crasheos en /command-center',
      'Monitoreo en vivo de respuestas de clientes',
    ],
    nextAction: 'Pipeline real conectado y visualizado.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },

  // ── 💡 LANZA SAAS BUILDER (0 a 1) ──
  {
    id: 'LNZ-01',
    key: 'lanza_idea_validation_flow',
    project: 'LANZA',
    title: 'Flujo de Validación Rápida de Ideas (Idea → Primera Venta)',
    owner: 'LANZA Lead',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Asistente de validación en 60 segundos con estructura de propuesta de valor, cálculo de costos y checkout Wompi/PSE.',
    acceptanceCriteria: [
      'Generación asistida en 60 segundos',
      'Integración con pasarela de pagos Wompi / PSE',
      'Panel interactivo en /command-center pestaña LANZA',
    ],
    nextAction: 'Panel de validación express integrado y probado.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'LNZ-02',
    key: 'lanza_unit_economics_calculator',
    project: 'LANZA',
    title: 'Simulador Financiero y Calculadora de Economía Unitaria',
    owner: 'Finanzas + Producto',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Herramienta de punto de equilibrio, margen de contribución y precio sugerido para micro-SaaS y nuevos negocios.',
    acceptanceCriteria: [
      'Cálculo en tiempo real de MRR potencial ($1.911.000 COP para 39 SaaS)',
      'Alertas de margen operativo',
      'Visualización clara en el panel comercial',
    ],
    nextAction: 'Integrado en las métricas de proyección de Lanza.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },

  // ── 💅 BRENDA BEAUTY OS & ACADEMIA PROFESIONAL ──
  {
    id: 'BRD-01',
    key: 'brenda_table_timer_protocol',
    project: 'BRENDA',
    title: 'Protocolo y Cronómetro de Mesa Profesional Rentable',
    owner: 'Brenda Lead + Mobile',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Protocolo de 6 fases de atención (Setup 3 min, Diagnóstico, Aplicación, Curado, Cobro) para maximizar ingresos por hora.',
    acceptanceCriteria: [
      'Desglose cronometrado por fase operativa',
      'Alertas de tiempo para evitar demoras en citas',
      'Cálculo de ganancia neta por servicio',
    ],
    nextAction: 'Panel visualizado en pestaña Brenda del Centro de Mando.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'BRD-02',
    key: 'brenda_sensory_menu_unit_costing',
    project: 'BRENDA',
    title: 'Menú de Experiencia Sensorial con Costeo Unitario por Insumo',
    owner: 'Brenda Pedagogía',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: '3 niveles de experiencia (Essential, Premium, VIP) con costeo exacto por insumo ($2.500 COP por detalle) vinculado al agendamiento.',
    acceptanceCriteria: [
      'Desglose de costo de insumos vs ganancia neta',
      'Menú sensorial estructurado por niveles',
      'Economía unitaria documentada',
    ],
    nextAction: 'Integrado en el panel Brenda Beauty OS.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },

  // ── ⚡ LA TRINIDAD COMERCIAL (ENRUTADOR Y GOBERNANZA) ──
  {
    id: 'TRN-01',
    key: 'trinidad_lead_router',
    project: 'TRINIDAD',
    title: 'Enrutador Inteligente de Leads de La Trinidad',
    owner: 'Holding Lead',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Algoritmo de clasificación que evalúa madurez digital y reseñas para enrutar: 0-5 res → LANZA, 5-50 res → GUAKI, +50 res → VEYRA.',
    acceptanceCriteria: [
      'Clasificación automática en tiempo real de 77 leads',
      'Despacho individual y por lote con un solo clic',
      'Proyección financiera unificada ($88,350 USD + $3,241,000 COP MRR)',
    ],
    nextAction: 'Componente TrinidadRouterCard operativo en Vista General.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'TRN-02',
    key: 'seo',
    project: 'TRINIDAD',
    title: 'Estrategia SEO/SEM Cruzada de La Trinidad',
    owner: 'Marketing',
    priority: 'P1',
    state: 'PASS',
    tone: 'green',
    description: 'Configuración de sitemaps XML dinámicos por ciudad (/sitemap.xml), robots.txt y LocalBusiness Schema para indexación en Google.',
    acceptanceCriteria: [
      'Sitemap dinámico generado con 32 rutas',
      'Schema.org estructurado',
      'Core Web Vitals optimizado',
    ],
    nextAction: 'Rutas /sitemap.xml y /robots.txt activas.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
  {
    id: 'TRN-03',
    key: 'backup',
    project: 'TRINIDAD',
    title: 'Seguridad, Aislamiento y Respaldo de Producción',
    owner: 'Propietario de Datos',
    priority: 'P0',
    state: 'PASS',
    tone: 'green',
    description: 'Protección estricta de rutas de administración contra despliegues públicos en Vercel y aislamiento de PostgreSQL en localhost.',
    acceptanceCriteria: [
      'Bloqueo 404 automático si host no es localhost (Vercel protegido)',
      'Bases de datos en PostgreSQL 5435 autenticadas',
      'Auditoría y trazabilidad completa',
    ],
    nextAction: 'Protección perimetral y RLS validadas.',
    targetSprint: 'Sprint 1',
    createdAt: '2026-08-16',
    completedAt: '2026-08-17',
  },
];
