export interface VeyraEnterpriseLead {
  id: string;
  name: string;
  category: string;
  city: string;
  phone: string;
  email: string;
  website: string;
  reviewsCount: number;
  rating: number;
  score: number;
  dealValue: number; // in USD, e.g. 2850
  status: 'contacted_smtp' | 'mri_ready' | 'interested' | 'meeting' | 'closed';
  bottleneck: string;
}

export const VEYRA_ENTERPRISE_LEADS: VeyraEnterpriseLead[] = [
  {
    id: 'veyra-01',
    name: 'Clínica Odontológica DentiSalud Especialistas',
    category: 'Odontología Especializada',
    city: 'Bogotá',
    phone: '+57 310 889 0011',
    email: 'contacto@dentisalud.com.co',
    website: 'https://dentisalud.com.co',
    reviewsCount: 142,
    rating: 4.8,
    score: 95,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de precalificador automático y retraso de 4h en confirmación de citas quirúrgicas',
  },
  {
    id: 'veyra-02',
    name: 'Centro de Cirugía Plástica & Estética Robles',
    category: 'Medicina Estética & Cirugía',
    city: 'Medellín',
    phone: '+57 312 445 6677',
    email: 'info@esteticarobles.com',
    website: 'https://esteticarobles.com',
    reviewsCount: 98,
    rating: 4.9,
    score: 94,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Atención manual de prospectos internacionales con pérdida del 45% de leads nocturnos',
  },
  {
    id: 'veyra-03',
    name: 'Bufete Jurídico & Corporativo Morales & Asoc.',
    category: 'Legal & Corporativo',
    city: 'Bogotá',
    phone: '+57 301 998 1122',
    email: 'gerencia@moralesasociados.co',
    website: 'https://moralesasociados.co',
    reviewsCount: 76,
    rating: 4.7,
    score: 92,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Filtrado manual de consultas laborales sin scoring de viabilidad de caso',
  },
  {
    id: 'veyra-04',
    name: 'Instituto Dermatológico del Poblado',
    category: 'Dermatología Médica',
    city: 'Medellín',
    phone: '+57 315 223 3445',
    email: 'citas@dermatologiapoblado.com',
    website: 'https://dermatologiapoblado.com',
    reviewsCount: 115,
    rating: 4.8,
    score: 93,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Sobrecarga de recepcionistas en WhatsApp sin agenda sincronizada con ERP',
  },
  {
    id: 'veyra-05',
    name: 'Clínica Oftalmológica Visión Láser Cali',
    category: 'Oftalmología Avanzada',
    city: 'Cali',
    phone: '+57 318 667 8899',
    email: 'atencion@visionlasercali.com',
    website: 'https://visionlasercali.com',
    reviewsCount: 88,
    rating: 4.7,
    score: 91,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Proceso de agendamiento de valoración refractiva no automatizado',
  },
  {
    id: 'veyra-06',
    name: 'Grupo Odontológico Sonrisa Real Barranquilla',
    category: 'Odontología & Implantes',
    city: 'Barranquilla',
    phone: '+57 300 778 9900',
    email: 'contacto@sonrisareal.co',
    website: 'https://sonrisareal.co',
    reviewsCount: 64,
    rating: 4.6,
    score: 89,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Tasa de no-show del 32% en valoraciones iniciales sin recordatorios multicanal',
  },
  {
    id: 'veyra-07',
    name: 'Centro Médico & Spa San Rafael',
    category: 'Salud & Bienestar',
    city: 'Bucaramanga',
    phone: '+57 311 334 5566',
    email: 'info@spasanrafael.com',
    website: 'https://spasanrafael.com',
    reviewsCount: 72,
    rating: 4.8,
    score: 90,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Sin pasarela de anticipos para paquetes de alto valor',
  },
  {
    id: 'veyra-08',
    name: 'Clínica Veterinaria Alta Especialidad 24 Horas',
    category: 'Veterinaria & Urgencias',
    city: 'Bogotá',
    phone: '+57 320 556 7788',
    email: 'urgencias@vet24alta.com',
    website: 'https://vet24alta.com',
    reviewsCount: 160,
    rating: 4.9,
    score: 96,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Llamadas de triaje manual que saturan la línea principal de urgencias',
  },
  {
    id: 'veyra-09',
    name: 'Centro de Rehabilitación Física & Fisioterapia Medellín',
    category: 'Fisioterapia & Kinesiología',
    city: 'Medellín',
    phone: '+57 314 990 1122',
    email: 'citas@fisiomedellin.co',
    website: 'https://fisiomedellin.co',
    reviewsCount: 83,
    rating: 4.8,
    score: 91,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Seguimiento de sesiones de terapia en papel sin historial digital del paciente',
  },
  {
    id: 'veyra-10',
    name: 'Ortodoncia Invisible & Digital Smile Bogotá',
    category: 'Ortodoncia Digital',
    city: 'Bogotá',
    phone: '+57 317 445 5566',
    email: 'info@digitalsmilebogota.com',
    website: 'https://digitalsmilebogota.com',
    reviewsCount: 130,
    rating: 4.9,
    score: 95,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Embudo de conversión de alineadores sin simulador interactivo de sonrisa',
  },
  {
    id: 'veyra-11',
    name: 'Firma de Contadores & Auditoría Tributaria Vega',
    category: 'Contabilidad & Auditoría',
    city: 'Cali',
    phone: '+57 313 778 8899',
    email: 'contacto@contadoresvega.co',
    website: 'https://contadoresvega.co',
    reviewsCount: 54,
    rating: 4.6,
    score: 88,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Onboarding manual de clientes corporativos con solicitud repetitiva de documentos',
  },
  {
    id: 'veyra-12',
    name: 'Clínica de Fertilidad & Reproducción Asistida Andes',
    category: 'Medicina Especializada',
    city: 'Bogotá',
    phone: '+57 316 112 2233',
    email: 'info@fertilidadandes.com',
    website: 'https://fertilidadandes.com',
    reviewsCount: 92,
    rating: 4.9,
    score: 94,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de canal confidencial automatizado para consultas sensibles de pacientes',
  },
  {
    id: 'veyra-13',
    name: 'Laboratorio Clínico & Genético Biogenética',
    category: 'Laboratorio Clínico',
    city: 'Medellín',
    phone: '+57 302 334 4455',
    email: 'resultados@biogenetica.co',
    website: 'https://biogenetica.co',
    reviewsCount: 105,
    rating: 4.7,
    score: 92,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Descarga manual de resultados de laboratorio por correo con alta fricción',
  },
  {
    id: 'veyra-14',
    name: 'Centro Odontológico Pediátrico Sonrisitas',
    category: 'Odontopediatría',
    city: 'Barranquilla',
    phone: '+57 305 667 7788',
    email: 'hola@sonrisitasdental.co',
    website: 'https://sonrisitasdental.co',
    reviewsCount: 68,
    rating: 4.8,
    score: 90,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de precalificador interactivo para padres y recordatorios vía WhatsApp',
  },
  {
    id: 'veyra-15',
    name: 'Ginecología & Obstetricia Integral Dra. Montoya',
    category: 'Ginecología',
    city: 'Medellín',
    phone: '+57 319 889 9900',
    email: 'dramontoya@ginecologiaintegral.co',
    website: 'https://ginecologiaintegral.co',
    reviewsCount: 78,
    rating: 4.9,
    score: 93,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Agendamiento de ecografías 4D por llamada telefónica sin pagos en línea',
  },
  {
    id: 'veyra-16',
    name: 'Centro Quiropráctico de la Sabana',
    category: 'Quiropráctica',
    city: 'Chía',
    phone: '+57 311 556 6677',
    email: 'citas@quiropracticasabana.com',
    website: 'https://quiropracticasabana.com',
    reviewsCount: 62,
    rating: 4.7,
    score: 89,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de sistema de suscripción mensual para tratamientos recurrentes',
  },
  {
    id: 'veyra-17',
    name: 'Psicología Clínica & Terapia de Pareja Renacer',
    category: 'Psicología & Salud Mental',
    city: 'Bogotá',
    phone: '+57 315 778 8899',
    email: 'terapia@psicologiarenacer.co',
    website: 'https://psicologiarenacer.co',
    reviewsCount: 85,
    rating: 4.9,
    score: 93,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Gestión de consultas virtuales sin sala de espera ni cobro automático previo',
  },
  {
    id: 'veyra-18',
    name: 'Centro de Podología Médica Pie Salud',
    category: 'Podología',
    city: 'Cali',
    phone: '+57 318 223 3344',
    email: 'info@piesaludcali.com',
    website: 'https://piesaludcali.com',
    reviewsCount: 59,
    rating: 4.6,
    score: 88,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Línea de WhatsApp colapsada en horarios pico sin bot de agendamiento 24/7',
  },
  {
    id: 'veyra-19',
    name: 'Centro Cardiológico & Diagnóstico No Invasivo',
    category: 'Cardiología',
    city: 'Bogotá',
    phone: '+57 321 445 5566',
    email: 'diagnostico@cardiologiacolombia.co',
    website: 'https://cardiologiacolombia.co',
    reviewsCount: 112,
    rating: 4.8,
    score: 94,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de portal de autogestión de citas para estudios Holter y pruebas de esfuerzo',
  },
  {
    id: 'veyra-20',
    name: 'Clínica Capilar Injerto Directo HairCare',
    category: 'Medicina Capilar',
    city: 'Medellín',
    phone: '+57 310 990 0011',
    email: 'valoraciones@haircarecolombia.com',
    website: 'https://haircarecolombia.com',
    reviewsCount: 95,
    rating: 4.9,
    score: 95,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de prediagnóstico fotográfico asistido por IA para cotizar implante capilar',
  },
  {
    id: 'veyra-21',
    name: 'Firma de Abogados Penalistas & Litigio Salazar',
    category: 'Derecho Penal',
    city: 'Bogotá',
    phone: '+57 312 667 7788',
    email: 'casos@salazarpenalistas.com',
    website: 'https://salazarpenalistas.com',
    reviewsCount: 66,
    rating: 4.7,
    score: 90,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Atención manual de casos urgentes sin categorización automática de gravedad',
  },
  {
    id: 'veyra-22',
    name: 'Centro de Otorrinolaringología & Voz del Valle',
    category: 'Otorrinolaringología',
    city: 'Cali',
    phone: '+57 317 889 9900',
    email: 'citas@orlvalle.com',
    website: 'https://orlvalle.com',
    reviewsCount: 71,
    rating: 4.7,
    score: 90,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Pérdida de pacientes en canal digital por no tener cotizador de nasosinuscopia',
  },
  {
    id: 'veyra-23',
    name: 'Centro de Nutrición & Medicina Funcional NutriVital',
    category: 'Nutrición & Funcional',
    city: 'Medellín',
    phone: '+57 314 334 4455',
    email: 'planes@nutrivital.co',
    website: 'https://nutrivital.co',
    reviewsCount: 89,
    rating: 4.9,
    score: 93,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de portal del paciente para ver planes alimenticios y seguimiento de peso',
  },
  {
    id: 'veyra-24',
    name: 'Clínica Veterinaria Especialistas Animal Care',
    category: 'Veterinaria',
    city: 'Bucaramanga',
    phone: '+57 301 556 6677',
    email: 'info@animalcarebga.com',
    website: 'https://animalcarebga.com',
    reviewsCount: 77,
    rating: 4.8,
    score: 91,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Carnet de vacunación digital no integrado con recordatorios automáticos',
  },
  {
    id: 'veyra-25',
    name: 'Centro de Implantes Dentales Dr. Restrepo',
    category: 'Implantología',
    city: 'Pereira',
    phone: '+57 315 990 0011',
    email: 'drrestrepo@implantespereira.co',
    website: 'https://implantespereira.co',
    reviewsCount: 84,
    rating: 4.9,
    score: 93,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Valoraciones de turismo dental sin flujo digital de recolección de tomografías',
  },
  {
    id: 'veyra-26',
    name: 'Consultoría Inmobiliaria & Avalúos Urbanos',
    category: 'Bienes Raíces & Avalúos',
    city: 'Bogotá',
    phone: '+57 318 445 5566',
    email: 'avaluos@urbanoscolombia.co',
    website: 'https://urbanoscolombia.co',
    reviewsCount: 63,
    rating: 4.6,
    score: 89,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Cotizaciones de avalúos comerciales realizadas en Excel sin firma electrónica',
  },
  {
    id: 'veyra-27',
    name: 'Centro de Medicina del Deporte SportMed',
    category: 'Medicina Deportiva',
    city: 'Medellín',
    phone: '+57 320 778 8899',
    email: 'contacto@sportmed.co',
    website: 'https://sportmed.co',
    reviewsCount: 102,
    rating: 4.9,
    score: 94,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de plataforma de evaluación biomecánica conectada a planes de entrenamiento',
  },
  {
    id: 'veyra-28',
    name: 'Instituto de Gastroenterología & Endoscopia Digestiva',
    category: 'Gastroenterología',
    city: 'Bogotá',
    phone: '+57 313 112 2233',
    email: 'citas@gastroandes.com',
    website: 'https://gastroandes.com',
    reviewsCount: 118,
    rating: 4.8,
    score: 94,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Instrucciones de preparación para colonoscopia enviadas por fotocopia en lugar de bot SMS/WA',
  },
  {
    id: 'veyra-29',
    name: 'Clínica Estética & Láser Belleza Médica Cali',
    category: 'Medicina Estética',
    city: 'Cali',
    phone: '+57 316 334 4455',
    email: 'info@bellezamedicacali.com',
    website: 'https://bellezamedicacali.com',
    reviewsCount: 91,
    rating: 4.8,
    score: 92,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Falta de agenda unificada para múltiples cabinas de depilación láser',
  },
  {
    id: 'veyra-30',
    name: 'Centro de Alergología & Inmunología Clínica',
    category: 'Alergología',
    city: 'Barranquilla',
    phone: '+57 302 556 6677',
    email: 'consultas@alergiascaribe.co',
    website: 'https://alergiascaribe.co',
    reviewsCount: 57,
    rating: 4.7,
    score: 88,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Seguimiento de pruebas de parche y vacunas sin recordatorios de aplicación',
  },
  {
    id: 'veyra-31',
    name: 'Centro de Ortodoncia Avanzada & Estética Dental',
    category: 'Ortodoncia & Estética',
    city: 'Cartagena',
    phone: '+57 305 889 9900',
    email: 'contacto@ortodonciacartagena.com',
    website: 'https://ortodonciacartagena.com',
    reviewsCount: 75,
    rating: 4.8,
    score: 91,
    dealValue: 2850,
    status: 'contacted_smtp',
    bottleneck: 'Atención de pacientes turistas sin confirmación anticipada en línea',
  },
];
